language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"

install:
  - npm install

services:
  - postgresql

env:
  global:
  - NODE_ENV=test

before_script:
  - psql -c 'create database barefoot_nomad_test;' -U postgres

script:
  - npm test
after_success: 
  - npm run coveralls
  